fix decryption script

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -30,6 +30,13 @@ env:
 before_install:
   - set -e
   - openssl aes-256-cbc -K $key_d499630087 -iv $iv_d499630087 -in "./scripts/gbq-enc-private.key.enc" -out "./scripts/gbq-enc-private.key" -d
+  - |-
+    if [ $(openssl sha1 "./scripts/gbq-enc-private.key" | egrep -o "[0-9a-f]+\$") != 965b2c53009fedf173b52ec16863ac9641e01ccf ]; then
+      echo "File gbq-enc-private.key failed to decrypt."
+      exit 1
+    else
+      echo "File gbq-enc-private.key successfully decrypted."
+    fi
   - scripts/decrypt_gbq_auth.sh
 
 install:
