google bigquery destination connector

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,5 +1,5 @@
 language: scala
-scala: 2.12.10
+scala: 2.12.8
 jdk: openjdk8
 
 cache:
@@ -13,14 +13,30 @@ env:
     - COURSIER_PROGRESS=0
     - SBT=./sbt
     # ENCRYPTION_PASSWORD
-    - secure: ...
+    - secure: "vJZnh9Z5GJ24oAXfGPTwjVc1gPcFmWu2PiQshaRmgeCWOHv+aTIUdbmRgUEeSbqxwRc2eS/+4Lz5qe+XIg4MfdTvI55njw8Wa9/G/VXAcA42Z37MDZ2vKJoRRZtMiqtb86evANeoP5jwpXjuaw9kAhdLI6xkSkXrkGlOshAaSKg2NSkLofU9GYWCt9fGBAhG9mlNqjkCtUSk1cb+xBzKJOrUFWYeHAXPhX32SkTIZ95MCQo1rPq0OKMNQbx74dQygukbzooIru3Za9S+6m+2OdPRmZoJ423E9w5P1uxANg6xb6NgvKWfiuNDjo8UAhWYssmc47UzAjD1DXQIQ5Gg9gN39EbiZfslNEIgQjcnGVTTTXKoZnTKTh1SYaVSb4KO9SwUWsuaXIXUb36dVnEpG8veBr5JErYPz1hAhcVWOqhekQVfa+eau6uYn0uovvtQ5JmbnhjSTBawNJfFJJeZO4X6HTaKRB86Hz2SkxyNhNCsmO8ml/uktZsIGJrfrfadBzA/FhNy9YE+yPftqopkV+L3p9KKXwybEdGYWiMd6LLxmZRnZ+w507PhlV3HzlKKzN642wrynPlIon3KTY3so+dx81cShkd84iLZuTdxa1hUxYIi85jdEZ4GQB6WpVmPxBkEN6f+456Lc3C7K/h34PI3oXveiEjI3rCsjgX+jkw="
     # GITHUB_TOKEN
-    - secure: ...
+    - secure: "TjgpfNIfUDmhWTSA95EjHr2rrHQgBPNTm42VQC8X3a4r1lTfZbxOdFfyL7DqM+KjU4YcXKvSpKz7qZ/1RR8vhQkZ1MjHEA/m9jydVS3JVkit8R37i8BX/FxUrX5PQjO/WQTEdXALzu5WjSlRYAexNUpKqmSGEfZMt2c/PRuqptFuMamZHI3VDamLvp8jzIv3LR+EOUjPF1rZHkDivDXgizPUAXu2PgU20I13eMe+Ctn43jzGJSnvLMkbeCGWKzhP0gqUWDdaxylk/hZXShXqsv9FBo1AwSu/l6+rDAAWpQ4FIFDnfdbNCHC8Btk+6WDcItQmHpvIDT1Ji/Mo6SdUpduI2StOlLiohdv0y2QfXGODJ6ONbfEBN7rjcWMO/HwNUnnaxxCX5Y7p8wHjTUZEAgY1XBfY6peUlc8OlNThrr8/RijcUVmr5ZZ7M60QmvsdDKfSH6rRK59aeJug7z+EjFLmj2hDmIJeVYITrH7HQQT99vXhIz81n9CCa1sQlbX+Ktc36Qn97u7K7QzngHKWVL/5gXrAdzDUpu7GR/x0rJhP7dsZwrVFwAGa7Jvn/rQ4dum+KyKAxVZm7I1KAxPQvA+ugya32ItJlfr6xZkLPKexzEf/fvYC6kpDhTUaB927KhpKsfyI2hjNG+WU+wvK/5khxeQvpVBaMwTKVl1cnKk="
     # GITHUB_ACCESS_TOKEN
-    - secure: ...
+    - secure: "UVXyURJBAkO5pW5Y2FGFP3WPYYIiwU+5hUi6tGaL060qHNjcI/L0jXfKLlJL4kG6Y7TuphD2OhcvBNt8J/zaAWLMMbJbvxWHOlGEqtyMfPf/OjKLTxGi2xDve0+Z83k7Bt21EVaJgpdNN7mfroHongC6mQJQmp6GAGwT4aEYRD+NB12T+0/qOtItXBrdAN3CgGTyf3nDH3lMWki28lSDGOO8/vaTABzYJS/47hw0lVrGoZukDEiKXEMnhfpNUt7ROqtLeemtXbznvFXEc0psKiaPfQ1UBMkt0vWcReh5ScaujyNw3MMFICUMgIOmD6TVWDaWyjQ7P0B6qVkyM45jhtVwHSSwHn7PV3bnv6U/yt9dFqCJDkIKIzi4ZpJ1JbsmiJaCoIvTJQShz4uUcPMFaovgVEre/awCWOruhq3y+DIOlBk99ljjBpowIXO4hTgf5vAM85OgE2ngKIqyZuDqd2hgI3a/RipEtBDqAMvfNZ+hWUbloiabjNesuzO9bem4vFCTqAGXcN8AjirsMq2OMGTjiWuai25mRSWYeoUUfPL1ucHZnDy1LI/psykQzEJAc1hDjU6AXeyO6dZCZvvrOWZMJzBwAKR8JtEzpiyTvtlNjewxtpWEyFURciRm69//Gri15303nS+8WiOdJgvN0k2PPm2zYeI/WVeD2uAA/3Y="
     # DISCORD_WEBHOOK_TOKENS
-    - secure: ...
+    - secure: "RSFYHWmWpfKCtR1dkwwmJ6lLvWaKPPMXF0EKa66tfUEybe17U4QdMX9iGMUl1KCEOj/5Sd+h2W9j4iA5OVl+pXZqcLDGt9amorx7nabKw8tcwgDDqHax6U6I4ogny/talOkQjq8UFSqEm4V+JXuL5mr0os4DkAkjjUqyTteYaq7WSA9JUzpbX2P6YgYksF00R6XWEw5nVKGa9GdAzMZXjN0RutfeJ8hwt2wSkr/bLtVmC9Kl9adp+3grqiSn5Qq2ooPZsaIdzmVFHSzH/PxMA6h/UoRqOQhxhazS8i5xI7ij+mmxDzOrewCx/GgrUSXrY941ng2MPcMnO3A7RcYw0ic0UzABx9w6CM20057OEbJn2Y6TRITuGiP7Oy3FX3brjChV+0Ye3n3Q0NaWwXZnHyDo0k6Grb5fPYALwWqikF6EjWYJUa4N+SYotZfZGpkV6BFIRsLOlvg08FlnXEGPcYq0pS6YxViqiR/K5KU5rN4EkL5Ip8woYO5M8XIoJk7f18/GI9UWyrx6rsjms+/iIuuT9bZR/F4SN/YEJDoaECSeuY1t3FUud105eEiaXj9Lgb0j2dxZs8pqlqb2AxeMBRd/nQ9Frp4Y6TIdvvMiKV3HZe23Ja9q7YsmfAGTF7XM9w8nbpJZ3ZV/JsHU4G3kHJHYkQlxmvKZLCKZW+Gi3Ns="
+    # GBQ_DECRYPT_PASSWORD
+    - secure: "jSBAaIaqc5M2jhh0DEYkfFh5Ax0ytxJwSmoN21jeZxPW2EhZoG6GyFGAIt4oE9cyS284vSL0JzR9MlVb+xR4tEDgC7cXDCowWNWxV476fFuCOjZ3wTYsTkpgCRmMcPSR3xsQouqkLOh5AFXul9CsaPXv451jYNsRnpxBYh3ACHd89cJ3iT1aGem++8k/HhMEkLsGbsYhCtmPYPPPrYuGyl1atE4yjLyznzVjYVeaQ+CFoetUmw1CYHwKtYhGdoRV4drXThVS60xCiByCBd69SZ6uco2PnVc6H5QlzyPhxVF6NGwC/7EJ/kCxVKohexjyfM2E9WU5UGb9bj73Q3GC/ezn3TNYkjRD78OdPzj+XTpq34qwVzr+psTp8Z80TqginW+3FhjV6Atga9Mn2Z1V3an3qZCglMhUn7XHCmO8+TZz2dRraFo+uIIHjs46iu+nrXbAACbdObH2RtjgXW1TpIJgx/lXu4eupp6EvP5sHJM5Uo3Ki/QXgL+LIjUB2v4rgAeaoBls9jTkHb7mUR2Kq5prrNbUxaChjv2ruZUVz+5v+1rw8sJ7GCMdcALPBy/q9AgLOWq6KmUP7h5Y2Fn1Igu0ikVMR45JjNVCAGPHk/tDS6zWimGmZkdU8620YgGTTvcMM8HyQd01w9LcBHBPnycPnFG+IZZ4aFrMeEywqZg="
+    # key for gbq-enc-private.key ($key_d499630087)
+    - secure: "mkQQeVmG/sZ7uQqWzTn5wzM/bWZ5n6xcvWnpbxoqoPGg5Rt0eTD+nFvxxPKLIO37RQiUOiZCQ10yCd73t8m7AyOdJZNdLItr/tQ41IFlAHXO4eZW6VvJZcYPUQPWBxztL9dynp5rGN+ftYJPDfXBavbKdEwXpkyiLSB6wnWnI4nsJfDmXWi/Co4yn8F4geQW8EilHV+f3WKPkqXa+9/mLnX69OYyYDObJifDkTmv7K11WAmHUTyDt5jGZHMUO2phVAKmnpHC2a8Y0H/WkjFpPJltjRUNfAWnz9BEyZ0qDbFouA/oJranEghNLOAVRoyXJAvJhkqS714hZ+Uh1NEEheVWFAQOZ5r+U8KEXIhvNb4NhQtv3Lx0cnidxG47k8s4yEn+eG9jyY7+THk1BFap9aQFGqKS12PyI0L81uDQLQpBXaLb7rlBaF9JXg8sy9poUggfKWtdOqYPSf6sQPtqnTofN9SEfHyaeh6HgqGOCHbGdIRiGHoaCclbZ5VItbbqYy5tm29jP4rrzVmZxwkDQq5msEplE19txzFvVElNbBbibKOTAritRIE2rQ7um+jXeFjF8BjQPhB7ptszN1qwIOMJg09qlgfQ1oHkS3dY3N1K8kneOcPkhE8Pjy2sPcSyCmIBlvFMVPesoyUUnjryq625Q3q4ScqMNsIoxmIni7k="
+    # initialization vector for gbq-enc-private.key ($iv_d499630087)
+    - secure: "mL+jKuoWikjoOh0ix9O5IJ97v4lBDAUVYtaANocNMpHKyiUXhmqgQjF1C6xw8TFDx/GsYw7sP8jVS6ATbaUV1kXKWvpEW1/4iDnZsLnZTwQb5ZaVrDsA8Yn1J2lhPUtXbWgNz8K3tjXWYQHWTzoS4z2dTcdudj7mvl+CuiAm0rHwD3noCQTVGtFKvhOJMf59iBseitGWWDDP3mDhbFsC5mmDi4OU4rR+UITWrFV/1qgMeEm3CDpwiPpLbHqPc95qAkCLY0B8WYP5PUwTsYFCzRrKPOSOSONYP9wOmOZz/EQm5xGx+MQX9fg2Ke/J7COFQP5n+NIC7PuBV+hVZV0pKjpbDMPfCkJll/E+c6QP06kAZYZK9s23QwuwQnx91xzmx+zO6omAF2yO+QIyqzrchjCln+hGycTzOqRFzP0TqlQS0PnoARO38ChLHwHF3gHHPmQNNDiwPy6vpMr14aBD13KJzgkDF7UDit+qsA85uLAdYm4NzO/4Di+dclK/r936ZkiWcWh3RcfMewKIURG07/LPTCKPBBkreczLvyaiSqmVwU3BiWNuKLmRs1lG+YwSlJ7Yx14Zi1pRi0tF1bT/RH5RT//gMaUEH5P3SMfXev7PgqzOdXZ17kC4QKPiJnX6CbddunqEMxiUBtH52v/FRPdl2eNbhUn2oscaSTfj4IY="
 
+before_install:
+  - set -e
+  - openssl aes-256-cbc -K $key_d499630087 -iv $iv_d499630087 -in "scripts/gbq-enc-private.key.enc" -out "scripts/gbq-enc-private.key" -d
+  - |-
+    if [ $(openssl sha1 "script/gbq-enc-private.key" | egrep -o "[0-9a-f]+\$") != 965b2c53009fedf173b52ec16863ac9641e01ccf ]; then
+      echo "File gbq-enc-private.key failed to decrypt"
+    else
+      exit 1
+    fi
+  - scripts/decrypt_gbq_auth.sh
 install:
   - mkdir scripts
   - $SBT transferCommonResources
@@ -48,3 +64,7 @@ branches:
   only:
     - master
     - /^backport.*$/
+
+before_cache:
+  - find "$HOME/.sbt/" -name '*.lock' -print0 | xargs -0 rm
+  - find "$HOME/.ivy2/" -name 'ivydata-*.properties' -print0 | xargs -0 rm
